### ISSUE TITLE
dep-switch.json目录结构是否可以调整一下？？

### ISSUE THREAD

**Issue by muyi-yang** [qiugang/DepSwitchPlugin#1]
Caused by: java.io.FileNotFoundException: /media/halove/work/android_HaloveFramework/common/dep-switch.json (没有那个文件或目录)
我把dep-switch.json放在项目根目录报这样的问题，必须要把dep-switch.json放入对于的module才能正常编译，这样很不方便，多个module就会有很多个dep-switch.json，如果能把dep-switch.json放在项目根目录，全局只有一个dep-switch.json文件，这样更合理，每次修改只关注这一个dep-switch.json。

**Comment by qiugang** [comment]
dep-switch 设计之初是针对 module 粒度的，不同 module 间可能是不同的维护人员，可以很好的控制。对于多个 module 都有共同依赖的可能切换的这种情况，可以考虑抽取一个 common module 提供依赖。

非常感谢你的反馈，后续可能会提供一种全局模式的配置针对这种情况。
